P2P/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('official.urls')),          # 平台主页路径
    path('captcha/', include('captcha.urls')),
    path('verify/', include("verify.urls")),
    path('petstate/', include('petstate.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # 这句话是用来指定和映射静态文件的路径

verify/urls.py
from django.urls import path
from . import views
app_name = 'verify'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('wel/', views.wel, name='wel'),
    path('register/', views.register, name='register'),
    path('secede/', views.secede, name='secede')
]

verify/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=12, default='', null=True, error_messages={"required": "用户名不能为空", })
    password = models.CharField(max_length=16, error_messages={"required": "密码不能为空", })
    email = models.EmailField()
    tel = models.CharField(max_length=13, validators=[
        RegexValidator(regex=r'^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$', message='手机号格式不对吧！')
    ])
    img = models.ImageField(upload_to="upload/user_msg/images")
    flower = models.TextField(max_length=65535, default='')
    star = models.TextField(max_length=65535, default='')
    cate = models.CharField(max_length=16, verbose_name='宠物科属')
    key = models.CharField(max_length=16, verbose_name='宠物品种')

    def __str__(self):
        return self.username

verify/forms.py
from django.forms import ModelForm, Widget
from django import forms
from .models import User
from captcha.fields import CaptchaField
from django.core.validators import ValidationError


class RegisterForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={"class": "inputs", "placeholder": "请输入密码", "value": "", "required": "required", }),
                               min_length=6, max_length=16, error_messages={"required": "密码不能为空", })

    class Meta:
        model = User
        exclude = ['img', 'flower', 'star', 'cate', 'key']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'inputs',
                'placeholder': '请输入用户名'
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'inputs',
                'placeholder': '请输入密码'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'inputs',
                'placeholder': '请输入邮箱'
            }),
            'tel': forms.TextInput(attrs={
                'class': 'inputs',
                'placeholder': '请输入手机号'
            })
        }

    def clean(self):
        cleaned_data = super().clean()
        tel = cleaned_data.get('tel', None)
        email = cleaned_data.get('email', None)
        print(tel, email)
        if tel and email:
            is_tel_exist = User.objects.filter(tel=tel).first()
            is_email_exist = User.objects.filter(email=email).first()
            if is_email_exist and is_tel_exist:
                raise ValidationError('该手机号和邮箱都已被人注册过了')
            if is_email_exist:
                raise ValidationError('该邮箱已被人注册过了')
            if is_tel_exist:
                raise ValidationError('该手机号已被人注册过了')


class LoginForm(ModelForm):
    # captcha = CaptchaField()    # django自带的图片验证

    class Meta:
        model = User
        exclude = ['captcha', 'email', 'username']
        fields = ('password', 'tel')
        error_messages = {
            'username': {
                'required': "用户名不能为空",
            },
        }
        widgets = {
            'tel': forms.TextInput(attrs={
                'class': 'inputs',
                'placeholder': '手机号/用户名',
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'inputs',
                'placeholder': '登录密码'
            })
        }

    def clean(self):
        cleaned_data = super().clean()
        tel = cleaned_data.get('tel', None)
        password = cleaned_data.get('password', None)
        if tel and password:
            res = User.objects.filter(tel=tel, password=password).first()
            if not res:
                raise ValidationError('用户名或密码有误！')

verify/views.py
from django.shortcuts import render, redirect, reverse
from .forms import LoginForm, RegisterForm
from django.contrib.auth.hashers import make_password, check_password
# Create your views here.


def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'verify/login.html', {'form': form})
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            tel = form.cleaned_data['tel']
            request.session['tel'] = tel
            return redirect(reverse("official:index"))
        else:
            error_msg = form.errors

            return render(request, 'verify/login.html', {'form': form, 'errors': error_msg})


def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        error_msg = form.errors
        return render(request, 'verify/register.html', {'form': form, 'errors': error_msg})
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            pass_word = request.POST.get("password", "")
            form.password = make_password(pass_word)
            form.save()
            return redirect(reverse('verify:login'))
        else:
            error_msg = form.errors
            return render(request, 'verify/register.html', {'form': form, 'errors': error_msg})


def wel(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'verify/wel.html', {'form': form})


def secede(request):
    if request.method == 'GET':
        del request.session['tel']
        return redirect(reverse("verify:login"))

verify/templates/verify/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_1003205_re4g9qd811a.css">
    <script src="{% static 'js/rem.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <style>
        *{
            margin: 0;
            padding: 0;
            list-style: none;
            font-family: PingFang SC, Helvetica Neue, Helvetica, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif;
        }
        a{
            text-decoration: none;
        }
        input::-webkit-input-placeholder {
            color: #ccc;
            opacity: 1;
            font-size: 0.33rem;
        }
        @keyframes hiddenMY{
            0%{
                opacity: 0;
            }
            50%{
                opacity: 1;
            }
            100%{
                opacity: 0;
            }
        }
        .main-box{
            width: 100%;
            background: url({% static 'img/bg3.jpg' %}) no-repeat;
            background-size: 100% 100%;
            overflow: hidden;
            position: relative;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            font-size: 18px;
        }
        .main-box:after{
            content: "";
            display: block;
        }
        .bg{
            width: 100%;
            height: 100%;
            background: rgba(0,0,0,.4);
            color: #fff;
         }
        .dlform{
            width: 100%;
            height: auto;
            padding-top: 2.8rem;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
        }
        .items{
            width: 90%;
            height: .8rem;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            margin: 0.2rem auto;
            position: relative;
            border-bottom: 1px solid #ccc;

        }
        .items:last-child{
            margin-top: 1rem;
        }
        .ul{
            width: 90%;
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin: .1rem auto 3.5rem;
        }
        .ul li a{
            color: #ccc;
            font-size: 0.31rem;
        }
        .inputs{
            padding: 0.1rem 3rem 0.1rem 0;
            border: 0;
            background: rgba(0,0,0,0);
            color: white;
            outline: none;
            font-size: .38rem;
        }
        .btn{
            width: 100%;
            height: .9rem;
            border: 0;
            border-radius: 0.08rem;
            background: #35A3F1;
            color: #fff;
            font-size: 0.4rem;
        }
        .icon-yonghu{
            margin: 0 .22rem .1rem 0;
            font-size: 0.38rem;
        }
        .icon-mima{
            margin: 0 .22rem .1rem 0;
            font-size: 0.38rem;
        }
        .thirdParty{
            width: 100%;
            height: 1rem;
            position: relative;
            font-size: 0.24rem;
            color: #ccc;
            text-align: center;
            padding-bottom: 1rem;
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            align-items: center;
        }
        .thirdParty span::before{
            content: '';
            width: 29%;
            height: 1px;
            background: #ccc;
            position: absolute;
            left: 0.3rem;
            top: 0.15rem;
        }
        .thirdParty span::after{
            content: '';
            width: 29%;
            height: 1px;
            background: #ccc;
            position: absolute;
            right: 0.3rem;
            top: 0.15rem;
        }
        .icon-weixinx{
            font-size: 0.65rem;
            color: green;
            margin-top: 0.35rem;
        }
        .error{
            width: 90%;
            height: auto;
            position: absolute;
            left: .3rem;
            bottom: 2.6rem;
            animation: hiddenMY 3s;
            opacity: 0;
        }
        .error .errorlist{
            width: 100%;
            height: 1.6rem;
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            align-items: center;
        }
        .errorlist li{
            width: 95%;
            height: 50%;
            {#line-height: 0.7rem;#}
            display: flex;
            justify-content: space-around;
            align-items: center;
        }
        .errorlist li .errorlist{
            width: 100%;
            height: 100%;
            line-height: 0.8rem;
        }
    </style>
</head>
<body>
    <div class="main-box">
        <div class="bg">
            <form action="" method="post" class="dlform" autocomplete="off">
                {% csrf_token %}
                <label for="" class="items">
                    <i class="iconfont icon-yonghu"></i>
                    {{ form.tel }}
                </label>
                <label for="" class="items">
                    <i class="iconfont icon-mima"></i>
                    {{ form.password }}
                </label>
                <label for="" class="items" style="border: 0">
                    <button class="btn">登 录</button>
                </label>
            </form>
            <div class="ul" >
                <li>
                    <a href="{% url 'verify:register' %}" style="text-decoration: underline;color: #35A3F1">快速注册</a>
                </li>
                <li>
                    <a href="">忘记密码?</a>
                </li>
            </div>
            <div class="thirdParty">
                <span>第三方账号快速登录</span>
                <i class="iconfont icon-weixinx"></i>
            </div>
            {% if errors %}
                <div class="error">
                    {{ errors }}
                </div>
            {% endif %}
        </div>
    </div>
</body>
</html>
<script>
    var oldtel = $("#id_tel").val();
    let tels=''
    if (oldtel !== ''){
        for (let i = 0;i<oldtel.length;i++){
            tels+=oldtel[i]
            if (i == 2){
                tels+=' '
            }
            if (i == 6){
                tels+=' '
            }
        }
        $("#id_tel").val(tels);
    }
     $("#id_tel").bind('input',function () {
            $("#id_tel").val(fomatterTel($("#id_tel").val(), oldtel));
            oldtel = $("#id_tel").val();
     });
    function fomatterTel(val, old) {
        var str = "";
        var telLen = val.length;
        if (old.length <= telLen) {
            if (telLen === 4 || telLen === 9) {
                var pre = val.substring(0, telLen-1);
                var last = val.substr(telLen-1, 1);
                str = pre + ' ' + last;
            } else {
                str = val;
            }
        } else {
            if (telLen === 9 || telLen === 4) {
                str = val.trim();
            } else {
                str = val;
            }
        }
        return str;
    }
    $(".btn").click(function () {
        let Posttel = ''
        oldtel = $("#id_tel").val();
        for (var i = 0; i< oldtel.length; i++){
            if (oldtel[i] != ' '){
               Posttel+=oldtel[i]
            }
        }
        $("#id_tel").val(Posttel)
    })
</script>

verify/templates/verify/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_1003205_re4g9qd811a.css">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <script src="{% static 'js/rem.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <style>
        *{
            margin: 0;
            padding: 0;
            list-style: none;
            font-family: PingFang SC, Helvetica Neue, Helvetica, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif;
        }
        a{
            text-decoration: none;
        }
        input::-webkit-input-placeholder {
            color: #ccc;
            opacity: 1;
            font-size: 0.33rem;
        }
        @keyframes hiddenMY{
            0%{
                opacity: 0;
            }
            50%{
                opacity: 1;
            }
            100%{
                opacity: 0;
            }
        }
        .main-box{
            width: 100%;
            background: url({% static 'img/bg3.jpg' %}) no-repeat;
            background-size: 100% 100%;
            overflow: hidden;
            position: relative;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            font-size: 18px;
        }
        .main-box:after{
            content: "";
            display: block;
        }
        .bg{
            width: 100%;
            height: 100%;
            background: rgba(0,0,0,.5);
            color: #fff;
         }
        .dlform{
            width: 100%;
            height: auto;
            padding-top: 2.8rem;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
        }
        .items{
            width: 90%;
            height: .8rem;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            margin: 0.2rem auto;
            position: relative;
            border-bottom: 1px solid #ccc;

        }
        .items:last-child{
            margin-top: 1rem;
        }
        .ul{
            width: 90%;
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin: .1rem auto 3rem;
        }
        .ul li a{
            color: #ccc;
            font-size: 0.31rem;
        }
        .inputs{
            padding: 0.1rem 3rem 0.1rem 0;
            border: 0;
            background: rgba(0,0,0,0);
            color: white;
            outline: none;
            font-size: .35rem;
        }
        .btn{
            width: 100%;
            height: .9rem;
            border: 0;
            border-radius: 0.08rem;
            background: #35A3F1;
            color: #fff;
            font-size: 0.4rem;
        }
        .icon-yonghu{
            margin: 0 .22rem .1rem 0;
            font-size: 0.38rem;
        }
        .icon-mima{
            margin: 0 .22rem .1rem 0;
            font-size: 0.38rem;
        }
        .icon-youxiang{
            margin: 0 .22rem .05rem 0;
            font-size: 0.28rem;
        }
        .icon-shouji{
            margin: 0 .22rem .1rem 0;
            font-size: 0.4rem;
        }
        .error{
            width: 90%;
            height: auto;
            position: absolute;
            left: .5rem;
            bottom: 0.6rem;
            animation: hiddenMY 4s;
            opacity: 0;
            font-family: PingFang SC, Helvetica Neue, Helvetica, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif;

        }
        .error .errorlist{
            {#width: 100%;#}
            height: 0.8rem;
            float: left;
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            align-items: center;
        }
        .errorlist li{
            height: 100%;
            line-height: 0.8rem;
        }
        .errorlist li .errorlist{
            line-height: 0.8rem;
        }
        input:-webkit-autofill {
            -webkit-box-shadow: 0 0 0px 1000px white inset;  //使用足够大的纯色内阴影覆盖黄色背景
            border: 1px solid #CCC!important;
        }
    </style>
</head>
<body>
    <div class="main-box">
        <div class="bg">
            <form action="" method="post" class="dlform" autocomplete="off">
                {% csrf_token %}
                <label for="" class="items">
                    <i class="iconfont icon-yonghu"></i>
                    {{ form.username }}
                </label>
                <label for="" class="items">
                    <i class="iconfont icon-shouji"></i>
                    {{ form.tel }}
                </label>
                <label for="" class="items">
                    <i class="iconfont icon-mima"></i>
                    {{ form.password }}
                </label>
                <label for="" class="items">
                    <i class="iconfont icon-youxiang"></i>
                    {{ form.email }}
                </label>
                <label for="" class="items" style="border: 0">
                    <button class="btn">注 册</button>
                </label>
            </form>
            <div class="ul">
                <li>
                    <a href="{% url 'verify:login' %}" style="text-decoration: underline;color: #35A3F1">已有账户?登录</a>
                </li>
            </div>
            {% if errors %}
                <div class="error">
                    {{ errors }}
                </div>
            {% endif %}
        </div>
    </div>
</body>
</html>
<script>
    {#  控制手机号的输入按3/4/4的格式显示  #}
    var oldtel = $("#id_tel").val();
    let tels=''
    if (oldtel !== ''){
        for (let i = 0;i<oldtel.length;i++){
            tels+=oldtel[i]
            if (i == 2){
                tels+=' '
            }
            if (i == 6){
                tels+=' '
            }
        }
        $("#id_tel").val(tels);
    }
     $("#id_tel").bind('input',function () {
        $("#id_tel").val(fomatterTel($("#id_tel").val(), oldtel));
        oldtel = $("#id_tel").val();
     });
    function fomatterTel(val, old) {
        var str = "";
        var telLen = val.length;
        if (old.length <= telLen) {
            if (telLen === 4 || telLen === 9) {
                var pre = val.substring(0, telLen-1);
                var last = val.substr(telLen-1, 1);
                str = pre + ' ' + last;
            } else {
                str = val;
            }
        } else {
            if (telLen === 9 || telLen === 4) {
                str = val.trim();
            } else {
                str = val;
            }
        }
        return str;
    }
    $(".btn").click(function () {
        let Posttel = ''
        oldtel = $("#id_tel").val();
        for (var i = 0; i< oldtel.length; i++){
            if (oldtel[i] != ' '){
               Posttel+=oldtel[i]
            }
        }
        $("#id_tel").val(Posttel)
    })
</script>

verify/templates/verify/wel.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <script src="{% static 'js/rem.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <style>
        *{
            margin: 0;
            padding: 0;
            list-style: none;
            font-family: PingFang SC, Helvetica Neue, Helvetica, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif;
        }
        a{
            text-decoration: none;
        }
        .wel-face{
            width: 100%;
            background: url({% static 'img/bg4.jpg' %}) no-repeat;
            background-size: 100% 100%;
            overflow: hidden;
            position: relative;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            font-size: 18px;
        }
        .wel-face:after{
            content: "";
            display: block;
            {#padding-top: 160%;#}
        }
        h3{
            margin: 3.5rem 0 7.5rem 0;
            font-size: 30px;
            color: white;
        }
        ul{
            width: 7rem;
            height: 1rem;
            margin: 0 auto 0.5rem;
            display: flex;
            justify-content: space-between;
        }
        li{
            width: 47%;
            height: 100%;
            background: white;
        }
        li:last-child{
            background: #38C0DC;
        }
        li:last-child a{
            color: #fff;
        }
        a{
            display: block;
            width: 100%;
            height: 100%;
            line-height: 1rem;
            text-align: center;
            color: black;
        }
    </style>
</head>
<body onload="setHeight()" onresize="setHeight()">
    <div class="wel-face" id="wel-face">
        <h3>遇 见 乐 宠</h3>
        <ul>
            <li>
                <a href="{% url 'verify:login' %}">
                    <span>登录</span>
                </a>
            </li>
            <li>
                <a href="{% url 'verify:register' %}">
                    <span>注册</span>
                </a>
            </li>
        </ul>
    </div>
</body>
</html>
<script type="text/javascript">
    function setHeight()
    {
        var max_height = document.documentElement.clientHeight;
        var primary = document.getElementById('wel-face');
        primary.style.minHeight = max_height+"px";
        primary.style.maxHeight = max_height+"px";
    }
</script>