P2P/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('official.urls')),          # 平台主页路径
    path('captcha/', include('captcha.urls')),
    path('verify/', include("verify.urls")),
    path('petstate/', include('petstate.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # 这句话是用来指定和映射静态文件的路径

official/urls.py
from django.urls import path
from . import views

app_name = 'official'
urlpatterns = [
    path('', views.index, name='index'),
    path('forecas/', views.forecas, name='forecas'),                            # 点赞处理路径
    path('lev_message/<int:item_id>', views.lev_message, name='lev_message'),   # 发表动态处理路径
    path('see_msg/<int:item_id>', views.see_msg, name='see_msg'),               # 查看评论
    path('set_info/<int:items>', views.set_info, name='set_info'),              # 个人主页
    path('about_me/', views.about_me, name='about_me'),                         # 个人信息主页
]

petstate/urls.py
from django.urls import path
from . import views

app_name = 'petstate'
urlpatterns = [
    path('write_TW', views.write_TW, name='write_TW'),
    path('intensify', views.intensify, name='intensify'),
    path('intensify_son', views.intensify_son, name='intensify_son'),
]

verify/urls.py
from django.urls import path
from . import views
app_name = 'verify'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('wel/', views.wel, name='wel'),
    path('register/', views.register, name='register'),
    path('secede/', views.secede, name='secede')
]

official/models.py
from django.db import models
from django.utils.html import SafeText

# Create your models here.


class Category(models.Model):
    petName = models.CharField(max_length=16, verbose_name='宠物类别')

    def listKeyword(self):
        objs = self.keyword_set.all()
        arr = []
        for obj in objs:
            arr.append("<e style='margin:0 8px;color:#ff6700;font-size:14px'>"+obj.name+"<e>")
        return SafeText(''.join(arr))
    listKeyword.short_description = "关键字"

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类管理'

    def __str__(self):
        return self.petName


class Keyword(models.Model):
    name = models.CharField(max_length=20, verbose_name='宠物类别的关键字')
    c = models.ForeignKey(to=Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

official/views.py
from django.shortcuts import render, reverse, redirect
from verify.models import User
from petstate.models import Tweet, Comment, Heart
from django.http import JsonResponse


# Create your views here.

# 主页路径处理函数
def index(request):
    if request.method == 'GET':
        tel = request.session.get('tel', None)
        if tel:
            real_true = User.objects.filter(tel=tel).first()
            if real_true.cate and real_true.key:
                flag = 1
            else:
                flag = 0
            Ema = real_true.email
            deal_email = Ema.split('@')
            data = Tweet.objects.all().order_by('-id')
            for item in data:
                uname = User.objects.filter(id=item.a_id).first()
                item.uname = uname
                url = item.img.url
                true_url = url.split("%7C")
                item.img = true_url
                for i in range(1, len(true_url)):
                    true_url[i] = '/media/'+true_url[i]
                item.length = len(true_url)
            # 查询点赞情况
            tel = request.session.get('tel', None)
            user_id = User.objects.get(tel=tel)
            about_heart = Heart.objects.all()
            arr_heart = set()
            # arr_user = set()
            for i in about_heart:
                demo1 = i.msg_id
                # demo2 = i.users_id
                arr_heart.add(demo1)
                # arr_user.add(demo2)
            for item in data:
                uid = Heart.objects.filter(msg_id=item.id).all()
                arr_user = set()
                for son in uid:
                    arr_user.add(son.users_id)
                # print(arr_user)
                item.true_heart = arr_heart
                item.true_user = arr_user
                item.art_user_img = item.a_id
                art_user_img = User.objects.filter(id=item.a_id).first()
                item.art_user_img= art_user_img.img
                print(item.art_user_img)
            # 登录用户头像的获取
            dl_user = User.objects.filter(tel=tel).first()
            return render(request, 'official/index.html', {'flag': flag, 'username': real_true.username, 'email': deal_email[0], 'data': data, "user_id": user_id.id,'dl_user':dl_user})
        else:
            return redirect(reverse("verify:login"))


# 动态点赞处理函数
def forecas(request):
    if request.is_ajax():
        msg_id = request.POST.get("msg_id", None)
        tel = request.session.get('tel', None)
        user_id = User.objects.get(tel=tel)
        heart = Heart.objects.filter(msg_id=int(msg_id)).all()
        heart_num = int(len(heart)) + 1
        print(msg_id, type(msg_id), user_id)
        YorN = Heart.objects.filter(msg_id=int(msg_id), users_id=int(user_id.id))
        print(YorN)
        if not YorN:
            Tweet.objects.filter(id=int(msg_id)).update(heart_num=heart_num)
            obj = Heart(msg_id=int(msg_id), users_id=int(user_id.id))
            obj.save()
            return JsonResponse({"statue": 'ok'})
        else:
            return JsonResponse({"statue": 'error'})
    if request.method == 'GET':
        return render(request,'official/forecas.html')
    # if request.method == 'POST':
    #     dis = request.POST.get('dis')
    #     roomnum = request.POST.get('roomnum')
    #     halls = request.POST.get('halls')
    #     floor = request.POST.get('floor')
    #     area = request.POST.get('area')
    #     subway = request.POST.get('subway')
    #     school = request.POST.get('school')
    #     print(dis, roomnum, halls, floor, area, subway, school)
    #     print(type(subway), type(school))
    #     yuce = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    #     if dis == '1':
    #         yuce[0] = 1
    #     elif dis == '2':
    #         yuce[1] = 1
    #     elif dis == '3':
    #         yuce[2] = 1
    #     elif dis == '4':
    #         yuce[3] = 1
    #     elif dis == '5':
    #         yuce[4] = 1
    #     if floor == 'low':
    #         yuce[5] = 1
    #     elif dis == 'middle':
    #         yuce[6] = 1
    #     yuce[7] = int(roomnum)
    #     yuce[8] = int(halls)
    #     yuce[9] = int(area)
    #     yuce[10] = int(subway)
    #     yuce[11] = int(school)
    #     print(yuce)
    #     df1 = pd.read_csv('house_price.csv')
    #     df2 = pd.get_dummies(df1[['dist', 'floor']])  # 虚拟变量,将汉字项转变为数字
    #     del df2['dist_chaoyang']                      # 他们每一种中的分类之间的关系很大，需要删除一列
    #     del df2['floor_high']
    #     del df1['dist']
    #     del df1['floor']
    #     pd.set_option('display.max_columns', 20)       # 输出的最大列数，避免省略
    #     df = pd.concat([df2, df1], axis=1)
    #     X = df.iloc[:, :-1]
    #     y = df['price']
    #     print(X.head(1))
    #     reg = LinearRegression()
    #     reg = reg.fit(X, y)
    #     price = reg.predict(np.array(yuce).reshape(1, -1))
    #     print(price)
    #     price = int(price[0])
    #     return render(request, 'official/forecas.html', {'price': price})


# 评论处理逻辑
def lev_message(request, item_id):
    if request.is_ajax():
        tel = request.session.get('tel', None)
        user_id = User.objects.get(tel=tel)
        msg_id = item_id
        con = request.POST.get('con', None)
        pl = Comment.objects.filter(msg_id=item_id).all()
        pl_num = int(len(pl))+1
        Tweet.objects.filter(id=int(item_id)).update(pl_num=pl_num)
        obj = Comment(con=con, msg_id=int(msg_id), users_id=int(user_id.id))
        obj.save()
        return JsonResponse({"statue": 'ok'})
    if request.method == 'GET':
        data = Tweet.objects.filter(id=item_id).first()
        a_id = data.a_id
        uname = User.objects.filter(id=a_id).first()
        return render(request, 'official/lev_message.html', {"data": data, 'uname': uname.username})


# 查看评论处理逻辑
def see_msg(request, item_id):
    if request.method == 'GET':
        data = Tweet.objects.filter(id=item_id).first()
        a_id = data.a_id
        uname = User.objects.filter(id=a_id).first()
        url = data.img.url
        true_url = url.split("%7C")
        data.img = true_url
        for i in range(1, len(true_url)):
            true_url[i] = '/media/' + true_url[i]
        data.length = len(true_url)
        command = Comment.objects.filter(msg_id=item_id).all()
        for item in command:
            print(item.users_id)
            demo = User.objects.filter(id=item.users_id).first()
            PL_user_name = demo.username
            item.users_id = PL_user_name
        return render(request, 'official/see_msg.html', {"data": data, 'uname': uname.username,'command':command})


# 个人信息设置处理函数
def set_info(request, items):
    if request.method == 'GET':
        tel = request.session.get('tel', None)
        real_true = User.objects.filter(tel=tel).first()
        Ema = real_true.email
        deal_email = Ema.split('@')
        data = Tweet.objects.filter(a_id=real_true.id).order_by('-id')
        for item in data:
            uname = User.objects.filter(id=item.a_id).first()
            item.uname = uname
            url = item.img.url
            true_url = url.split("%7C")
            item.img = true_url
            for i in range(1, len(true_url)):
                true_url[i] = '/media/' + true_url[i]
            item.length = len(true_url)
        # 查询点赞情况
        user_id = User.objects.get(tel=tel)
        about_heart = Heart.objects.filter(users_id=user_id)
        arr_heart = set()
        for i in about_heart:
            demo1 = i.msg_id
            # demo2 = i.users_id
            arr_heart.add(demo1)
            # arr_user.add(demo2)
        for item in data:
            uid = Heart.objects.filter(msg_id=item.id).all()
            arr_user = set()
            for son in uid:
                arr_user.add(son.users_id)
            print(arr_user)
            item.true_heart = arr_heart
            item.true_user = arr_user
        # 用户头像获取
        dl_user = User.objects.filter(tel=tel).first()
        return render(request, 'official/set_info.html', {'username': real_true.username, 'data': data, 'email': deal_email[0], "user_id": user_id.id, "items": items,"dl_user":dl_user})



import os,base64


# 个人信息设置
def about_me(request):
    if request.method == 'GET':
        tel = request.session.get('tel', None)
        real_true = User.objects.filter(tel=tel).first()
        dl_user = User.objects.filter(tel=tel).first()
        return render(request, 'official/about_me.html', {'username': real_true.username,"dl_user":dl_user})
    if request.method == 'POST':
        img_data = request.POST.get('img_data', None)
        nan = img_data.split(",")
        img_name = request.session.get('tel', None)

        file = open(os.path.join('upload/user_img/images/' + img_name+'.png'), 'wb')
        print(file)
        file.write(base64.b64decode(nan[1]))
        file.close()
        a_id = User.objects.filter(tel=img_name).first()

        User.objects.filter(id=int(a_id.id)).update(img='/user_img/images/' + img_name+'.png')
        return JsonResponse({"statue": 'ok'})

official/templates/official/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <script src="{% static 'js/rem.js' %}"></script>
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_1003205_sisnl9crnj9.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <style>
        .write_TW{
            display: block;
            width: 1.1rem;
            height: 1.1rem;
            background: #1DA1F2;
            position: fixed;
            right: 0.4rem;
            bottom: 0.4rem;
            border-radius: 50%;
            box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.22) 0px 3px 6px;
        }
        .icon-tianjia{
            font-size: 0.25rem;
            position: absolute;
            left: 0.3rem;
            top: 0.4rem;
            color: #fff;

        }
        .icon-feather-{
            font-size: 0.5rem;
            position: absolute;
            left: 0.45rem;
            top: 0.3rem;
            color: #fff;
        }
        .icon-ziyuan1{
            color: red;
        }
    </style>
</head>
<body>
    <div class="con">
        <div class="header">
            <a href="javaScript:;" class="userImg">
                <img src="/media{{ dl_user.img }}" alt="">
            </a>
            <div class="CardTips">
                <h2>主页</h2>
            </div>
        </div>
        <div class="listCard">
            <ul class="item">
                <li><i class="iconfont icon-zhuye"></i></li>
                <li><i class="iconfont icon-sousuo1"></i></li>
                <li><i class="iconfont icon-tongzhi"></i></li>
                <li><i class="iconfont icon-youjian"></i></li>
            </ul>
        </div>
        <div class="content">
            {% for item in data %}
                <ul class="Tweet">
                    <div class="left_con">
                        <a href="">
                            <img src="/media{{ item.art_user_img }}" alt="">
                        </a>
                    </div>
                    <div class="right_con">
                        <li class="text">
                            <span>{{ item.uname }}</span>
                            <span>{{ item.c_time }}</span>
                            <p>
                                <a href="{% url "official:see_msg" item.id%}" style="color: rgba(0,0,0,1)">
                                    {{ item.con }}
                                </a>
                            </p>
                        </li>
                        <li class="images">
                            {% if item.length == 1 %}
                                {% for i in item.img %}
                                    <img src="{{ i }}" alt="" style="width: 100%;height: 100%">
                                {% endfor %}
                            {% endif %}
                            {% if item.length == 2 %}
                                {% for i in item.img %}
                                    <img src="{{ i }}" alt="" style="width: 50%;height: 100%">
                                {% endfor %}
                            {% endif %}
                            {% if item.length == 3 %}
                                {% for i in item.img %}
                                    <img src="{{ i }}" alt="" class="spe">
                                {% endfor %}
                            {% endif %}
                            {% if item.length == 4 %}
                                {% for i in item.img %}
                                    <img src="{{ i }}" alt="" style="width: 50%;height: 100%">
                                {% endfor %}
                            {% endif %}
                        </li>
                        <li class="list_item">
                            <a href="{% url 'official:lev_message' item.id %}">
                                <i class="iconfont icon-xiaoxi"></i>
                                <span>{{ item.pl_num }}</span>
                            </a>
                            <a href="">
                                <i class="iconfont icon-xunhuan"></i>
                                <span>{{ item.transpond }}</span>
                            </a>
                            <a href="javaScript:;" class="likeYou">
                                {% if item.id in item.true_heart and user_id in item.true_user %}
                                    <i class="iconfont icon-ziyuan1"></i>
                                    <span class="smart_heart">{{ item.heart_num }}</span>
                                    <span hidden class="msg_id">{{ item.id }}</span>
                                    {% else %}
                                    <i class="iconfont icon-xihuan"></i>
                                    <span class="smart_heart">{{ item.heart_num }}</span>
                                    <span hidden class="msg_id">{{ item.id }}</span>
                                {% endif %}
                            </a>
                        </li>
                    </div>
                </ul>
            {% endfor %}
        </div>
        <div class="Msg_setting">
            <i class="iconfont icon-guanbi"></i>
            <ul>
                <li>
                    <div class="p_msg">
                        <img src="/media{{ dl_user.img }}" alt="">
                        {# 跳至个人主页 #}
                        <a href="{% url 'official:set_info' 0 %}">
                            <b>{{ username }}</b>
                            <em>@{{ email }}</em>
                        </a>
                    </div>
                </li>
                <li class="linkMe">
                    <a href="">
                        <span>72</span>
                        <strong>正在关注</strong>
                    </a>
                    <a href="">
                        <span>64</span>
                        <strong>关注者</strong>
                    </a>
                </li>
                <li class="aboutMe">
                    <a href="{% url 'official:set_info' 0 %}">
                        <i class="iconfont icon-yonghu"></i>
                        <span>个人资料</span>
                    </a>
                    <a href="">
                        <i class="iconfont icon-liebiao"></i>
                        <span>列表</span>
                    </a>
                    <a href="">
                        <i class="iconfont icon-shuqian"></i>
                        <span>书签</span>
                    </a>
                    <a href="{% url 'official:forecas' %}">
                        <i class="iconfont icon-shandian"></i>
                        <span>瞬间</span>
                    </a>
                </li>
                <li class="trueSetting">
                    <a href=""><span>设置和隐私</span></a>
                    <a href=""><span>关于</span></a>
                    <a href="{% url 'verify:secede' %}"><span>退出登录</span></a>
                </li>
            </ul>
        </div>
        {% if flag == 0 %}
            <a class="write_TW" href="{% url 'petstate:intensify' %}">
                <i class="iconfont icon-tianjia"></i>
                <i class="iconfont icon-feather-"></i>
            </a>
            {% else %}
            <a class="write_TW" href="{% url 'petstate:write_TW' %}">
                <i class="iconfont icon-tianjia"></i>
                <i class="iconfont icon-feather-"></i>
            </a>
        {% endif %}

    </div>
</body>
</html>
<script>
    $('.spe').eq(0).css({
        width: '50%',
        height: '50%'
    })
    $('.spe').eq(1).css({
        width: '50%',
        height: '50%'
    })
    $('.spe').eq(2).css({
        width: '50%',
        height: '50%'
    })
    console.log($('.spe').eq(1))
    $(".userImg").click(function () {
        $(".Msg_setting").css('display','block')
        $(".con").css({
            background: 'rgba(0,0,0,.1)'
        })
    })
    $(".icon-guanbi").click(function () {
        $(".Msg_setting").css('display','none')
        $(".con").css({
            background: '#fff'
        })
    })
    //滑动处理
        var startX, startY;
        document.addEventListener('touchstart',function (ev) {
            startX = ev.touches[0].pageX;
            startY = ev.touches[0].pageY;
        }, false);
                function GetSlideDirection(startX, startY, endX, endY) {
            var dy = startY - endY;
            //var dx = endX - startX;
            var result = 0;
            if(dy>0) {//向上滑动
                result=1;
                console.log(1)
            }else if(dy<0){//向下滑动
                result=2;
                console.log(2)
            }
            else
            {
                result=0;
            }
            return result;
        }
        document.addEventListener('touchend',function (ev) {
            var endX, endY;
            endX = ev.changedTouches[0].pageX;
            endY = ev.changedTouches[0].pageY;
            var direction = GetSlideDirection(startX, startY, endX, endY);
            switch(direction) {
                case 0:
                    break;
                case 1:
                    // 向上
                    $(".listCard").css('top','0')
                    $(".header").css('top','-1rem')
                    break;
                case 2:
                    // 向下
                    $(".listCard").css('top','1rem')
                    $(".header").css('top','0')
                    break;
                default:
            }
        }, false);
    $(".likeYou").click(function (e) {
        $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}'}});
        let that=$(this)
        console.log(that.find(".true_heart").text())
        console.log($(this).find('.msg_id').text())

        $.ajax({
            url: '{% url 'official:forecas' %}',
            type: 'post',
            data: {"msg_id":$(this).find('.msg_id').text()},
            success:function (e) {
                if (e.statue=='ok'){
                    that.find('.iconfont').removeClass('icon-xihuan')
                    that.find('.iconfont').addClass("icon-ziyuan1")
                    let demo = parseInt(that.find('.smart_heart').text())+1
                    that.find('.smart_heart').text(demo)
                }else {
                    alert("老铁,你给他点过了！")
                }
            }
        })
    })
</script>

official/templates/official/set_info.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <script src="{% static 'js/rem.js' %}"></script>
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_1003205_sisnl9crnj9.css">
    <link rel="stylesheet" href="{% static 'css/set_info.css' %}">
    <style>
        .top{
            width: 100%;
            height: 3.5rem;
            background: url("{% static 'img/top_bg2.png' %}") no-repeat;
            background-size: 100% 100%;
        }
    </style>
</head>
<body>
    <div class="content">
        <div class="top">
            <div class="con">
                <a href="{% url 'official:index' %}">
                    <i class="iconfont icon-fanhui"></i>
                </a>
            </div>
        </div>
        <div class="middle">
            <li>
                <a href="" class="img">
                    <div class="userImg">
                        <img src="/media{{ dl_user.img }}" alt="">
                    </div>
                </a>
                <a href="{% url 'official:about_me' %}" class="info">
                    <span>编辑宠物资料</span>
                </a>
            </li>
            <li>
                <span>{{ username }}</span>
                <span>@{{ email }}</span>
                <p>个性签名......</p>
            </li>
            <li>
               <span>76 <em>正在关注</em></span>
               <span style="margin-left: .2rem">6 <em>关注者</em></span>
            </li>
        </div>
        <div class="tweet_list">
            {% if items == 0 %}
                <div class="items">
                    <a class="dt" href="{% url 'official:set_info' 0 %}" style="color: #35A3F1;border-bottom: 0.03rem solid #35A3F1">
                        <span>动态</span>
                    </a>
                    <a class="hf" href="{% url 'official:set_info' 1 %}">
                        <span>回复</span>
                    </a>
                    <a class="xh" href="{% url 'official:set_info' 2 %}">
                        <span>喜欢</span>
                    </a>
                </div>
                <div class="many">
                    {% for item in data %}
                        <ul class="Tweet">
                            <div class="left_con">
                                <a href="">
                                    <img src="{% static 'img/boy.png' %}" alt="">
                                </a>
                            </div>
                            <div class="right_con">
                                <li class="text">
                                    <span>{{ item.uname }}</span>
                                    <span>{{ item.c_time }}</span>
                                    <p>{{ item.con }}</p>
                                </li>
                                <li class="images">
                                    {% if item.length == 1 %}
                                        {% for i in item.img %}
                                            <img src="{{ i }}" alt="" style="width: 100%;height: 100%">
                                        {% endfor %}
                                    {% endif %}
                                    {% if item.length == 2 %}
                                        {% for i in item.img %}
                                            <img src="{{ i }}" alt="" style="width: 50%;height: 100%">
                                        {% endfor %}
                                    {% endif %}
                                    {% if item.length == 3 %}
                                        {% for i in item.img %}
                                            <img src="{{ i }}" alt="" class="spe">
                                        {% endfor %}
                                    {% endif %}
                                    {% if item.length == 4 %}
                                        {% for i in item.img %}
                                            <img src="{{ i }}" alt="" style="width: 50%;height: 100%">
                                        {% endfor %}
                                    {% endif %}
                                </li>
                                <li class="list_item">
                                    <a href="{% url 'official:lev_message' item.id %}">
                                        <i class="iconfont icon-xiaoxi"></i>
                                        <span>{{ item.pl_num }}</span>
                                    </a>
                                    <a href="">
                                        <i class="iconfont icon-xunhuan"></i>
                                        <span>{{ item.transpond }}</span>
                                    </a>
                                    <a href="javaScript:;" class="likeYou">
                                        {% if item.id in item.true_heart and user_id in item.true_user %}
                                            <i class="iconfont icon-ziyuan1"></i>
                                            <span class="smart_heart">{{ item.heart_num }}</span>
                                            <span hidden class="msg_id">{{ item.id }}</span>
                                            {% else %}
                                            <i class="iconfont icon-xihuan"></i>
                                            <span class="smart_heart">{{ item.heart_num }}</span>
                                            <span hidden class="msg_id">{{ item.id }}</span>
                                        {% endif %}
                                    </a>
                                </li>
                            </div>
                        </ul>
                    {% endfor %}
                </div>
                {% elif items == 1 %}
                <div class="items">
                    <a class="dt" href="{% url 'official:set_info' 0 %}">
                        <span>动态</span>
                    </a>
                    <a class="hf" href="{% url 'official:set_info' 1 %}" style="color: #35A3F1;border-bottom: 0.03rem solid #35A3F1">
                        <span>回复</span>
                    </a>
                    <a class="xh" href="{% url 'official:set_info' 2 %}">
                        <span>喜欢</span>
                    </a>
                </div>
                <div class="many">
                    <h3>这是回复消息区</h3>
                </div>
                {% elif items == 2 %}
                <div class="items">
                    <a class="dt" href="{% url 'official:set_info' 0 %}">
                        <span>动态</span>
                    </a>
                    <a class="hf" href="{% url 'official:set_info' 1 %}">
                        <span>回复</span>
                    </a>
                    <a class="xh" href="{% url 'official:set_info' 2 %}" style="color: #35A3F1;border-bottom: 0.03rem solid #35A3F1">
                        <span>喜欢</span>
                    </a>
                </div>
                <div class="many">
                    <h3>这是喜欢动态区</h3>
                </div>
            {% endif %}
        </div>
    </div>
</body>
</html>
<script>
    $(".likeYou").click(function (e) {
        $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}'}});
        let that=$(this)
        console.log(that.find(".true_heart").text())
        console.log($(this).find('.msg_id').text())

        $.ajax({
            url: '{% url 'official:forecas' %}',
            type: 'post',
            data: {"msg_id":$(this).find('.msg_id').text()},
            success:function (e) {
                if (e.statue=='ok'){
                    that.find('.iconfont').removeClass('icon-xihuan')
                    that.find('.iconfont').addClass("icon-ziyuan1")
                    let demo = parseInt(that.find('.smart_heart').text())+1
                    that.find('.smart_heart').text(demo)
                }else {
                    alert("老铁,你给他点过了！")
                }
            }
        })
    })
</script>